export default {
  rain: '🌧',
  snow: '❄️',
  sleet: '🌨',
  wind: '💨',
  fog: '🌫',
  cloudy: '☁️',
  hail: '💦',
  thunderstorm: '⛈',
  tornado: '🌪',
  'partly-cloudy-day': '⛅️',
  'partly-cloudy-night': '⛅️',
  'clear-day': '☀️',
  'clear-night': '🌕',
};
